version: '3.8'

name: gc-admin-local

services:
# DB
  admindb:
    container_name: gc-admindb
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: gc_admin
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./.docker/db/data:/var/lib/mysql  
      - ./.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3309:3306"
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

# PHP Swoole
  swoole:
    container_name: gc-swoole
    env_file:
      - .env.local
    build: 
      context: .
      dockerfile: .docker/php-swoole/Dockerfile
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    ports:
      - "8006:8000"
    tty: true
    depends_on:
      admindb:
        condition: service_healthy

  node:
    container_name: gc-node
    env_file:
      - .env.local
    build:
      target: development
      context: .
      dockerfile: .docker/node/Dockerfile
    volumes:
      - .:/node:cached
      - node_modules:/node/node_modules
    ports:
      - "8007:8000"
    tty: true

volumes:
  node_modules:
